"use client";

// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import LasyBridgeScript from "@/components/lasy-bridge-script";

export const metadata: Metadata = {
  title: "DSD Finance Hub",
  description:
    "Sistema financeiro inteligente de conciliação bancária e relatórios.",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head></head>
      <body className="antialiased">
        <LasyBridgeScript />
        {children}
      </body>
    </html>
  );
}
