/* eslint-disable header/header */
/* @auto-fix-disable */
/* @formatter:off */
// The layout must remain a Server Component. Do NOT add "use client".
import "../lib/fonts";

export const metadata: Metadata = {
  title: "DSD Finance Hub",
  description: "Sistema financeiro inteligente de conciliação bancária e relatórios.",
};

// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

export const metadata: Metadata = {
  title: "DSD Finance Hub",
  description:
    "Sistema financeiro inteligente de conciliação bancária e relatórios.",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
