-- ===========================================
-- QUERIES PARA DIAGNOSTICAR O BANCO HUBSPOT
-- Conecte ao servidor: datawarehouse-io-eur.database.windows.net
-- Database: Jorge9660
-- ===========================================

-- 1) LISTAR TODAS AS TABELAS DISPONÍVEIS
SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

-- 2) VER ESTRUTURA DA TABELA DE DEALS (colunas disponíveis)
-- Execute após descobrir o nome exato da tabela de deals
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE '%Deal%'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- 3) PROCURAR TABELAS DE PAGAMENTO/ORDERS/INVOICES
SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Payment%'
   OR TABLE_NAME LIKE '%Invoice%'
   OR TABLE_NAME LIKE '%Order%'
   OR TABLE_NAME LIKE '%LineItem%'
   OR TABLE_NAME LIKE '%Transaction%'
   OR TABLE_NAME LIKE '%Product%';

-- 4) PROCURAR COLUNAS ESPECÍFICAS (order_id, transaction_id, etc.)
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE '%order%' 
   OR COLUMN_NAME LIKE '%transaction%' 
   OR COLUMN_NAME LIKE '%paid%'
   OR COLUMN_NAME LIKE '%payment%'
ORDER BY TABLE_NAME, COLUMN_NAME;

-- 5) VER AMOSTRA DOS DEALS (ajuste o nome da tabela se necessário)
-- SELECT TOP 20 * FROM Deals ORDER BY createdate DESC;

-- 6) PROCURAR TABELAS DE ASSOCIAÇÃO
SELECT TABLE_SCHEMA, TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Association%'
   OR TABLE_NAME LIKE '%Contact%'
   OR TABLE_NAME LIKE '%Company%'
ORDER BY TABLE_NAME;
